configure infrastructure new

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,7 +1,62 @@
 version: 2.1
 
 commands:
-  
+  install_ansible:
+    description: Install Ansible
+    steps:
+      -run:
+        name: Install Ansible
+        command: |
+          sudo apt update
+          sudo apt install software-properties-common -y
+          sudo add-apt-respository --yes --update ppa:ansible/ansible
+          sudo apt install ansible -y
+
+commands:
+  destroy-environment:
+    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
+    parameters:
+      # Add parameter here
+      workflow_Id:
+        default: "${CIRCLE_WORKFLOW_ID:0:7}"
+        type: string
+
+    steps:
+      - run:
+          name: Destroy environments
+          when: on_fail
+          command: |
+            aws s3 rm s3://udapeople-<<parameters.workflow_id>> --recursive
+            aws cloudformation delete-stack --stack-name "udapeople-backend-<<parameters.workflow_id>>"
+            aws cloudformation delete-stack --stack-name "udapeople-frontend-<<parameters.workflow_id>>"
+            # Your code here
+            exit 1
+
+  revert-migrations:
+    description: Revert the last migration if successfully run in the current workflow.
+    parameters:
+      # Add parameter here
+      workflow_Id:
+        default: "${CIRCLE_WORKFLOW_ID:0:7}"
+        type: string
+    steps:
+      - run:
+          name: Revert migrations
+          when: on_fail
+          # Add when this will run
+          command: |
+            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
+            SUCCESS=$(curl --insecure https://kvdb.io/AA7NfcqrTmoisVLbyUtrLC/migration_<<parameters.workflow_id >>)  
+            # Logic for reverting the database state
+              
+            if (( $SUCCESS == 1 ));
+            then
+                cd ~/project/backend
+                npm install
+                npm run build
+                npm run migration:revert
+            fi
+
 jobs:
   build-frontend:
     docker:
@@ -180,6 +235,66 @@ jobs:
           paths:
             - project/.circleci/ansible/inventory.txt
       # Here's where you will add some code to rollback on failure
+
+  configure-infrastructure:
+    docker:
+      # Docker image here that supports Ansible
+      - image: cimg/base:stable
+    steps:
+      - checkout
+      # Checkout code from git
+      # Add ssh keys with fingerprint
+      - add_ssh_keys:
+        fingerprints:
+          - "a6:5a:93:96:be:e0:d6:fa:5e:c6:e8:1d:ad:b8:86:8c"
+      # attach workspace
+      - attach_workspace:
+          at: ~/
+      - install_ansible
+            
+      - run:
+          name: Configure server
+          command: |
+            # Your code here
+            cd .circleci/ansible
+            cat inventory.txt
+            ansible-playbook -i inventory.txt configure-server.yml
+      
+      # Destroy-environment on fail     
+      - destroy-environment:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+
+  run-migrations:
+    docker:
+      # Docker image here that supports NodeJS
+      - image: circleci/node:13.8.0
+    steps:
+      # Checkout code from git
+      - checkout
+
+      - run:
+          name: Run migrations
+          command: |
+            # Your code here
+            cd backend
+            npm install
+            npm run migrations > migrations_dump.txt
+            
+      - run:
+          name: Send migration results to kvdb
+          command: |
+            # Your code here
+            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+            then
+            curl --insecure https://kvdb.io/XvmnYuBT7skCdxBkm1h13X/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '1'
+            fi
+      - destroy-environment
+      - revert-migrations
+
+
+            exit 1
+      # Here's where you will add some code to rollback on failure
+
 workflows:
   default:
     jobs:
@@ -198,3 +313,7 @@ workflows:
           filters:
             branches:
               only: [master]
+      - configure-infrastructure:
+          requires: [deploy-infrastructure]
+      - run-migrations:
+          requires: [configure-infrastructure]
